# Generated by Django 5.0.7 on 2024-09-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='shares',
        ),
    ]
