# Generated by Django 5.0.7 on 2024-09-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0004_remove_profile_followers_profile_following'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='emojis',
            new_name='emoji_counts',
        ),
        migrations.AddField(
            model_name='meme',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MemeEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=2)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='meme_app.meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meme', 'user')},
            },
        ),
    ]
