# Generated by Django 5.0.7 on 2024-09-11 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0005_rename_emojis_meme_emoji_counts_meme_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.RemoveField(
        model_name='meme',
        name='retweets',
    ),
]
