# Generated by Django 5.0.7 on 2024-09-11 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0006_retweet_alter_meme_retweets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meme')},
            },
        ),
        migrations.AddField(
            model_name='meme',
            name='retweets',
            field=models.ManyToManyField(related_name='retweeted_memes', through='meme_app.Retweet', to=settings.AUTH_USER_MODEL),
        ),
    ]
