# Generated by Django 5.0.7 on 2024-09-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0007_retweet_meme_retweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
